# Generated by Buildr 1.4.17, change to your liking


# Version number for this release
VERSION_NUMBER = "0.2.1"
# Group identifier for your projects
GROUP = "LoCALISM"
COPYRIGHT = "François Cabrol"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

Project.local_task :run

desc "The Localism project"
define "LoCALISM" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "Localism" do
    compile.with Dir['lib/LeapJava.jar']
    package(:jar)
  end

  define "MouseExample" do
    compile.with projects("Localism"), Dir['lib/LeapJava.jar']
    package(:jar)
  end

  task :run => :compile do
    system 'java -cp MouseExample/target/classes:Localism/target/classes:lib/LeapJava.jar -Djava.library.path=lib/  com.cabrol.francois.localism.example.mouse.Localism'
  end

end
